constants = {
    "WORD_CHAR": r"\w",
    "ANY_CHAR": r".",
    "DIGIT": r"\d",
    "NON_DIGIT": r"\D",
    "BOUNDARY": r"\b",
    "SPACE": r"\s",
    "TAB": r"\t",
    "NEWLINE": r"\n",
    "NON_WORD": r"\W",
    "RETURN": r"\r",
    "DOT": r"\.",
    "BACKSLASH": r"\\",
    "ALPHA": r"[a-zA-Z]",
    "BLANK": r"[ \t]",
    "PUNCTUATION": r"[!\"\#$%&'()*+,\-./:;<=>?@\[\\\]^_‘{|}~]",
    "UPPER_CHAR": r"[A-Z]",
    "LOWER_CHAR": r"[a-z]",
    "HEXDIGIT": r"[A-Fa-f0-9]",
    "ALNUM": r"\w",
    "NON_ALNUM": r"\W",
    "WORD": r"\b(\w+)\b",
    "QUOTATION": r'"',
    "WHITESPACE": r"\s",
    "NON_WHITESPACE": r"\S",
    "BAR": r"\|",
    "START": r"^",
    "END": r"$",
    "DASH": r"\-",
}
