# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.api_error_rate_limit_exceeded_response import ApiErrorRateLimitExceededResponse


class TooManyRequestsError(ApiError):
    def __init__(self, body: ApiErrorRateLimitExceededResponse):
        super().__init__(status_code=429, body=body)
