"""
    HCL AppScan on Cloud (v2)

    This API allows you to interact with the service. The API allows you to perform many of the operations available in the UI and more.</br>For authentication, use the relevant APIs in the Account section. A successful authentication response includes a bearer token for use in subsequent API calls. Pasting this token in the 'Access token' field above will automatically add the authorization header to any API call that requires a valid session.

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

from pyasoc.configuration import Configuration


class AppScanSaaSModelsV2ScanExecutionInfo:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"scan_name": "str", "scan_id": "str", "execution_id": "str"}

    attribute_map = {
        "scan_name": "ScanName",
        "scan_id": "ScanId",
        "execution_id": "ExecutionId",
    }

    def __init__(self, scan_name=None, scan_id=None, execution_id=None, _configuration=None):
        """AppScanSaaSModelsV2ScanExecutionInfo - a model defined in Swagger"""
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._scan_name = None
        self._scan_id = None
        self._execution_id = None
        self.discriminator = None

        if scan_name is not None:
            self.scan_name = scan_name
        if scan_id is not None:
            self.scan_id = scan_id
        if execution_id is not None:
            self.execution_id = execution_id

    @property
    def scan_name(self):
        # type: () -> str
        """Gets the scan_name of this AppScanSaaSModelsV2ScanExecutionInfo.


        :return: The scan_name of this AppScanSaaSModelsV2ScanExecutionInfo.
        :rtype: str
        """
        return self._scan_name

    @scan_name.setter
    def scan_name(self, scan_name):
        """Sets the scan_name of this AppScanSaaSModelsV2ScanExecutionInfo.


        :param scan_name: The scan_name of this AppScanSaaSModelsV2ScanExecutionInfo.
        :type: str
        """

        self._scan_name = scan_name

    @property
    def scan_id(self):
        # type: () -> str
        """Gets the scan_id of this AppScanSaaSModelsV2ScanExecutionInfo.


        :return: The scan_id of this AppScanSaaSModelsV2ScanExecutionInfo.
        :rtype: str
        """
        return self._scan_id

    @scan_id.setter
    def scan_id(self, scan_id):
        """Sets the scan_id of this AppScanSaaSModelsV2ScanExecutionInfo.


        :param scan_id: The scan_id of this AppScanSaaSModelsV2ScanExecutionInfo.
        :type: str
        """

        self._scan_id = scan_id

    @property
    def execution_id(self):
        # type: () -> str
        """Gets the execution_id of this AppScanSaaSModelsV2ScanExecutionInfo.


        :return: The execution_id of this AppScanSaaSModelsV2ScanExecutionInfo.
        :rtype: str
        """
        return self._execution_id

    @execution_id.setter
    def execution_id(self, execution_id):
        """Sets the execution_id of this AppScanSaaSModelsV2ScanExecutionInfo.


        :param execution_id: The execution_id of this AppScanSaaSModelsV2ScanExecutionInfo.
        :type: str
        """

        self._execution_id = execution_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(AppScanSaaSModelsV2ScanExecutionInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppScanSaaSModelsV2ScanExecutionInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AppScanSaaSModelsV2ScanExecutionInfo):
            return True

        return self.to_dict() != other.to_dict()
