"""
    HCL AppScan on Cloud (v2)

    This API allows you to interact with the service. The API allows you to perform many of the operations available in the UI and more.</br>For authentication, use the relevant APIs in the Account section. A successful authentication response includes a bearer token for use in subsequent API calls. Pasting this token in the 'Access token' field above will automatically add the authorization header to any API call that requires a valid session.

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

from pyasoc.configuration import Configuration


class UserSiteCommonModelsExploreItem:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"file_id": "str", "multi_step": "bool"}

    attribute_map = {"file_id": "FileId", "multi_step": "MultiStep"}

    def __init__(self, file_id=None, multi_step=None, _configuration=None):
        """UserSiteCommonModelsExploreItem - a model defined in Swagger"""
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._file_id = None
        self._multi_step = None
        self.discriminator = None

        if file_id is not None:
            self.file_id = file_id
        if multi_step is not None:
            self.multi_step = multi_step

    @property
    def file_id(self):
        # type: () -> str
        """Gets the file_id of this UserSiteCommonModelsExploreItem.


        :return: The file_id of this UserSiteCommonModelsExploreItem.
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id):
        """Sets the file_id of this UserSiteCommonModelsExploreItem.


        :param file_id: The file_id of this UserSiteCommonModelsExploreItem.
        :type: str
        """

        self._file_id = file_id

    @property
    def multi_step(self):
        # type: () -> bool
        """Gets the multi_step of this UserSiteCommonModelsExploreItem.


        :return: The multi_step of this UserSiteCommonModelsExploreItem.
        :rtype: bool
        """
        return self._multi_step

    @multi_step.setter
    def multi_step(self, multi_step):
        """Sets the multi_step of this UserSiteCommonModelsExploreItem.


        :param multi_step: The multi_step of this UserSiteCommonModelsExploreItem.
        :type: bool
        """

        self._multi_step = multi_step

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(UserSiteCommonModelsExploreItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserSiteCommonModelsExploreItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserSiteCommonModelsExploreItem):
            return True

        return self.to_dict() != other.to_dict()
