"""
    HCL AppScan on Cloud (v2)

    This API allows you to interact with the service. The API allows you to perform many of the operations available in the UI and more.</br>For authentication, use the relevant APIs in the Account section. A successful authentication response includes a bearer token for use in subsequent API calls. Pasting this token in the 'Access token' field above will automatically add the authorization header to any API call that requires a valid session.

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

from pyasoc.configuration import Configuration


class UserSiteCommonModelsCommentModelResponse:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "comment": "str",
        "date_created": "datetime",
        "created_by": "UserSiteCommonModelsBasicUserInfo",
    }

    attribute_map = {
        "comment": "Comment",
        "date_created": "DateCreated",
        "created_by": "CreatedBy",
    }

    def __init__(self, comment=None, date_created=None, created_by=None, _configuration=None):
        """UserSiteCommonModelsCommentModelResponse - a model defined in Swagger"""
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._comment = None
        self._date_created = None
        self._created_by = None
        self.discriminator = None

        if comment is not None:
            self.comment = comment
        if date_created is not None:
            self.date_created = date_created
        if created_by is not None:
            self.created_by = created_by

    @property
    def comment(self):
        # type: () -> str
        """Gets the comment of this UserSiteCommonModelsCommentModelResponse.


        :return: The comment of this UserSiteCommonModelsCommentModelResponse.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this UserSiteCommonModelsCommentModelResponse.


        :param comment: The comment of this UserSiteCommonModelsCommentModelResponse.
        :type: str
        """

        self._comment = comment

    @property
    def date_created(self):
        # type: () -> datetime
        """Gets the date_created of this UserSiteCommonModelsCommentModelResponse.


        :return: The date_created of this UserSiteCommonModelsCommentModelResponse.
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this UserSiteCommonModelsCommentModelResponse.


        :param date_created: The date_created of this UserSiteCommonModelsCommentModelResponse.
        :type: datetime
        """

        self._date_created = date_created

    @property
    def created_by(self):
        # type: () -> UserSiteCommonModelsBasicUserInfo
        """Gets the created_by of this UserSiteCommonModelsCommentModelResponse.


        :return: The created_by of this UserSiteCommonModelsCommentModelResponse.
        :rtype: UserSiteCommonModelsBasicUserInfo
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this UserSiteCommonModelsCommentModelResponse.


        :param created_by: The created_by of this UserSiteCommonModelsCommentModelResponse.
        :type: UserSiteCommonModelsBasicUserInfo
        """

        self._created_by = created_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(UserSiteCommonModelsCommentModelResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserSiteCommonModelsCommentModelResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserSiteCommonModelsCommentModelResponse):
            return True

        return self.to_dict() != other.to_dict()
