
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-04T16:08:57+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf025e9c51da2e84298dc3056e71c08e1cb2fcdf",
 "version": "1.2.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
