# Generated by Django 4.1 on 2023-04-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreplus_tags", "0002_category_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_id",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Category ID"
            ),
        ),
    ]
