# coding: utf-8

"""
    Mantium API

    Mantium API Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.438
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from mantium_spec.configuration import Configuration


class DatamodelPageApplicationResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'items': 'list[ApplicationResponse]',
        'total': 'int',
        'page': 'int',
        'size': 'int'
    }

    attribute_map = {
        'items': 'items',
        'total': 'total',
        'page': 'page',
        'size': 'size'
    }

    def __init__(self, items=None, total=None, page=None, size=None, local_vars_configuration=None):  # noqa: E501
        """DatamodelPageApplicationResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._items = None
        self._total = None
        self._page = None
        self._size = None
        self.discriminator = None

        self.items = items
        self.total = total
        self.page = page
        self.size = size

    @property
    def items(self):
        """Gets the items of this DatamodelPageApplicationResponse.  # noqa: E501


        :return: The items of this DatamodelPageApplicationResponse.  # noqa: E501
        :rtype: list[ApplicationResponse]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this DatamodelPageApplicationResponse.


        :param items: The items of this DatamodelPageApplicationResponse.  # noqa: E501
        :type items: list[ApplicationResponse]
        """
        if self.local_vars_configuration.client_side_validation and items is None:  # noqa: E501
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items

    @property
    def total(self):
        """Gets the total of this DatamodelPageApplicationResponse.  # noqa: E501


        :return: The total of this DatamodelPageApplicationResponse.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this DatamodelPageApplicationResponse.


        :param total: The total of this DatamodelPageApplicationResponse.  # noqa: E501
        :type total: int
        """
        if self.local_vars_configuration.client_side_validation and total is None:  # noqa: E501
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                total is not None and total < 0):  # noqa: E501
            raise ValueError("Invalid value for `total`, must be a value greater than or equal to `0`")  # noqa: E501

        self._total = total

    @property
    def page(self):
        """Gets the page of this DatamodelPageApplicationResponse.  # noqa: E501


        :return: The page of this DatamodelPageApplicationResponse.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this DatamodelPageApplicationResponse.


        :param page: The page of this DatamodelPageApplicationResponse.  # noqa: E501
        :type page: int
        """
        if self.local_vars_configuration.client_side_validation and page is None:  # noqa: E501
            raise ValueError("Invalid value for `page`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                page is not None and page < 1):  # noqa: E501
            raise ValueError("Invalid value for `page`, must be a value greater than or equal to `1`")  # noqa: E501

        self._page = page

    @property
    def size(self):
        """Gets the size of this DatamodelPageApplicationResponse.  # noqa: E501


        :return: The size of this DatamodelPageApplicationResponse.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this DatamodelPageApplicationResponse.


        :param size: The size of this DatamodelPageApplicationResponse.  # noqa: E501
        :type size: int
        """
        if self.local_vars_configuration.client_side_validation and size is None:  # noqa: E501
            raise ValueError("Invalid value for `size`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                size is not None and size < 1):  # noqa: E501
            raise ValueError("Invalid value for `size`, must be a value greater than or equal to `1`")  # noqa: E501

        self._size = size

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatamodelPageApplicationResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DatamodelPageApplicationResponse):
            return True

        return self.to_dict() != other.to_dict()
