from .functions import correlation
from .functions import find_best_model_classification
from .functions import find_best_model_regression
from .functions import find_best_clustering_algorithm
from .functions import find_best_model_regression_2
from .functions import tune_MLPc_parameters
from .functions import tune_MLPr_parameters
from .functions import plot_target_vs_others
from .functions import plot_target_vs_others_normalized
from .functions import plot_side_by_side
from .functions import evaluate_model
from .functions import outliers