VERSION_YEAR = 2023
VERSION_MONTH = int('07')
VERSION_DAY = int('04')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('54')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202307041554
version_date = '2023/07/04 15:54'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
