VERSION_YEAR = 2023
VERSION_MONTH = int('07')
VERSION_DAY = int('06')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('50')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202307061550
version_date = '2023/07/06 15:50'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
