
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-05T15:46:16+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "0189d8db3cedfc1a5fafb6e3edff1ea29662b3be",
 "version": "1.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
