# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binary_op.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x62inary_op.proto\x12\x0bjijmodeling"\x8c\x02\n\x08\x42inaryOp\x12(\n\x04kind\x18\x01 \x01(\x0e\x32\x1a.jijmodeling.BinaryOp.Kind\x12\x0f\n\x07left_id\x18\x02 \x01(\x04\x12\x10\n\x08right_id\x18\x03 \x01(\x04"\xb2\x01\n\x04Kind\x12\x14\n\x10KIND_UNSPECIFIED\x10\x00\x12\x0c\n\x08KIND_POW\x10\x01\x12\x0c\n\x08KIND_MOD\x10\x02\x12\x0b\n\x07KIND_EQ\x10\x03\x12\x0f\n\x0bKIND_NOT_EQ\x10\x04\x12\x12\n\x0eKIND_LESS_THAN\x10\x05\x12\x15\n\x11KIND_LESS_THAN_EQ\x10\x06\x12\x15\n\x11KIND_GREATER_THAN\x10\x07\x12\x18\n\x14KIND_GREATER_THAN_EQ\x10\x08\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "binary_op_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _BINARYOP._serialized_start = 33
    _BINARYOP._serialized_end = 301
    _BINARYOP_KIND._serialized_start = 123
    _BINARYOP_KIND._serialized_end = 301
# @@protoc_insertion_point(module_scope)
