# -*- coding: utf-8 -*-

"""
ctddocumentation

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from ctddocumentation.api_helper import APIHelper


class User(object):

    """Implementation of the 'User' model.

    TODO: type model description here.

    Attributes:
        username (string): TODO: type description here.
        password (string): TODO: type description here.
        first_name (string): TODO: type description here.
        last_name (string): TODO: type description here.
        mail (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "username": 'username',
        "password": 'password',
        "first_name": 'first_name',
        "last_name": 'last_name',
        "mail": 'mail'
    }

    _optionals = [
        'first_name',
        'last_name',
        'mail',
    ]

    def __init__(self,
                 username=None,
                 password=None,
                 first_name=APIHelper.SKIP,
                 last_name=APIHelper.SKIP,
                 mail=APIHelper.SKIP):
        """Constructor for the User class"""

        # Initialize members of the class
        self.username = username 
        self.password = password 
        if first_name is not APIHelper.SKIP:
            self.first_name = first_name 
        if last_name is not APIHelper.SKIP:
            self.last_name = last_name 
        if mail is not APIHelper.SKIP:
            self.mail = mail 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        username = dictionary.get("username") if dictionary.get("username") else None
        password = dictionary.get("password") if dictionary.get("password") else None
        first_name = dictionary.get("first_name") if dictionary.get("first_name") else APIHelper.SKIP
        last_name = dictionary.get("last_name") if dictionary.get("last_name") else APIHelper.SKIP
        mail = dictionary.get("mail") if dictionary.get("mail") else APIHelper.SKIP
        # Return an object of this model
        return cls(username,
                   password,
                   first_name,
                   last_name,
                   mail)
