# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decision_var.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x64\x65\x63ision_var.proto\x12\x0bjijmodeling"\x87\x04\n\x0b\x44\x65\x63isionVar\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.jijmodeling.DecisionVar.Type\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tshape_ids\x18\x03 \x03(\x04\x12\x33\n\x0blower_bound\x18\x04 \x01(\x0b\x32\x1e.jijmodeling.DecisionVar.Bound\x12\x33\n\x0bupper_bound\x18\x05 \x01(\x0b\x32\x1e.jijmodeling.DecisionVar.Bound\x1a\xb7\x01\n\x05\x42ound\x12\x31\n\x04type\x18\x01 \x01(\x0e\x32#.jijmodeling.DecisionVar.Bound.Type\x12\x10\n\x08\x62ound_id\x18\x02 \x01(\x04"i\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fTYPE_EXPRESSION\x10\x01\x12\x14\n\x10TYPE_PLACEHOLDER\x10\x02\x12 \n\x1cTYPE_SUBSCRIPTED_PLACEHOLDER\x10\x03"\x85\x01\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bTYPE_BINARY\x10\x01\x12\x10\n\x0cTYPE_INTEGER\x10\x02\x12\x13\n\x0fTYPE_CONTINUOUS\x10\x03\x12\x15\n\x11TYPE_SEMI_INTEGER\x10\x04\x12\x18\n\x14TYPE_SEMI_CONTINUOUS\x10\x05\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "decision_var_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _DECISIONVAR._serialized_start = 36
    _DECISIONVAR._serialized_end = 555
    _DECISIONVAR_BOUND._serialized_start = 236
    _DECISIONVAR_BOUND._serialized_end = 419
    _DECISIONVAR_BOUND_TYPE._serialized_start = 314
    _DECISIONVAR_BOUND_TYPE._serialized_end = 419
    _DECISIONVAR_TYPE._serialized_start = 422
    _DECISIONVAR_TYPE._serialized_end = 555
# @@protoc_insertion_point(module_scope)
