from typing import TypeVar

from .EventContainer import EventContainer
from .BaseEvent import BaseEvent
from .EventEXPChange import EventEXPChange
from .EventCustom import EventCustom
from .EventRecvMessage import EventRecvMessage
from .EventWrappedScript import EventWrappedScript
from .EventAirChange import EventAirChange
from .CodeCompileEvent import CodeCompileEvent
from .EventResourcePackLoaded import EventResourcePackLoaded
from .EventItemDamage import EventItemDamage
from .EventJoinedTick import EventJoinedTick
from .EventTitle import EventTitle
from .EventJoinedRecvPacket import EventJoinedRecvPacket
from .EventOpenContainer import EventOpenContainer
from .EventBossbar import EventBossbar
from .EventAttackBlock import EventAttackBlock
from .EventDamage import EventDamage
from .EventPlayerLeave import EventPlayerLeave
from .EventChunkLoad import EventChunkLoad
from .EventHungerChange import EventHungerChange
from .EventDropSlot import EventDropSlot
from .EventHealthChange import EventHealthChange
from .EventRiding import EventRiding
from .EventEntityUnload import EventEntityUnload
from .EventJoinServer import EventJoinServer
from .EventLaunchGame import EventLaunchGame
from .EventEntityDamaged import EventEntityDamaged
from .EventStatusEffectUpdate import EventStatusEffectUpdate
from .EventFallFlying import EventFallFlying
from .EventDisconnect import EventDisconnect
from .EventInteractBlock import EventInteractBlock
from .EventSendPacket import EventSendPacket
from .EventHeal import EventHeal
from .EventJoinedSendPacket import EventJoinedSendPacket
from .EventInteractEntity import EventInteractEntity
from .EventBlockUpdate import EventBlockUpdate
from .EventEntityHealed import EventEntityHealed
from .EventClickSlot import EventClickSlot
from .EventDimensionChange import EventDimensionChange
from .EventItemPickup import EventItemPickup
from .EventQuitGame import EventQuitGame
from .EventOpenScreen import EventOpenScreen
from .EventDeath import EventDeath
from .EventAttackEntity import EventAttackEntity
from .EventSignEdit import EventSignEdit
from .EventRecvPacket import EventRecvPacket
from .EventSendMessage import EventSendMessage
from .CommandContextHelper import CommandContextHelper
from .EventJoinedKey import EventJoinedKey
from .EventTick import EventTick
from .EventSound import EventSound
from .EventKey import EventKey
from .EventProfileLoad import EventProfileLoad
from .EventService import EventService
from .EventEntityLoad import EventEntityLoad
from .EventChunkUnload import EventChunkUnload
from .EventArmorChange import EventArmorChange
from .EventPlayerJoin import EventPlayerJoin
from .EventHeldItemChange import EventHeldItemChange

File = TypeVar("java.io.File")

