# Generated by Django 4.1.5 on 2023-02-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notify',
            field=models.BooleanField(default=False),
        ),
    ]
