# Generated by Django 4.1.5 on 2023-02-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0005_projectstatus_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
