# Generated by Django 4.1.7 on 2023-06-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_center', '0012_alter_projectactivity_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='pin',
            field=models.BooleanField(default=False, help_text='Pin activity to top of list', verbose_name='Pinned'),
        ),
    ]
