# Generated by Django 3.2.12 on 2022-02-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postbuero', '0002_maildomain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maildomain',
            options={'permissions': (('can_use_domain', 'Can use domain'),)},
        ),
    ]
