# Generated by Django 3.2.12 on 2022-02-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbuero', '0003_alter_maildomain_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maildomain',
            name='allowed_groups',
        ),
        migrations.AddField(
            model_name='maildomain',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public usable'),
        ),
    ]
