# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: number_lit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10number_lit.proto\x12\x0bjijmodeling"\x85\x01\n\tNumberLit\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.jijmodeling.NumberLit.Type\x12\r\n\x05value\x18\x02 \x01(\x04">\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x0e\n\nTYPE_FLOAT\x10\x01\x12\x10\n\x0cTYPE_INTEGER\x10\x02\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "number_lit_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _NUMBERLIT._serialized_start = 34
    _NUMBERLIT._serialized_end = 167
    _NUMBERLIT_TYPE._serialized_start = 105
    _NUMBERLIT_TYPE._serialized_end = 167
# @@protoc_insertion_point(module_scope)
