
from CToolKit.amalgamation import  generate_amalgamated_code
from CToolKit.ComandLineExecution import ComandLineExecution
from CToolKit.comand_line_functions import compile_project_by_command
from CToolKit.comand_line_functions import compile_project
from CToolKit.comand_line_functions import test_binary_with_valgrind
from CToolKit.comand_line_functions import execute_test_for_file
from CToolKit.comand_line_functions import execute_test_for_folder


from CToolKit.Errors.CopilationError import CopilationError
from CToolKit.Errors.CopilationWarning import CopilationWarning
from CToolKit.Errors.ExecutionError import ExecutionError
from CToolKit.Errors.ValgrindError import ValgrindError
from CToolKit.Errors.ValgrindLeak import ValgrindLeak
from CToolKit.Errors.NotExpectedResult import NotExpectedResult

from CToolKit.readme_converter import include_code_in_markdown