
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-05T21:58:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "41861f3f1868951596ce3be5a2b6c57f53614853",
 "version": "0.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
