"""
    HCL AppScan on Cloud (v2)

    This API allows you to interact with the service. The API allows you to perform many of the operations available in the UI and more.</br>For authentication, use the relevant APIs in the Account section. A successful authentication response includes a bearer token for use in subsequent API calls. Pasting this token in the 'Access token' field above will automatically add the authorization header to any API call that requires a valid session.

    OpenAPI spec version: v2

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

from pyasoc.configuration import Configuration


class MicrosoftDataODataQuerySemanticAstSelectExpandClause:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "selected_items": "list[MicrosoftDataODataQuerySemanticAstSelectItem]",
        "all_selected": "bool",
    }

    attribute_map = {"selected_items": "SelectedItems", "all_selected": "AllSelected"}

    def __init__(self, selected_items=None, all_selected=None, _configuration=None):
        """MicrosoftDataODataQuerySemanticAstSelectExpandClause - a model defined in Swagger"""
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._selected_items = None
        self._all_selected = None
        self.discriminator = None

        if selected_items is not None:
            self.selected_items = selected_items
        if all_selected is not None:
            self.all_selected = all_selected

    @property
    def selected_items(self):
        # type: () -> list[MicrosoftDataODataQuerySemanticAstSelectItem]
        """Gets the selected_items of this MicrosoftDataODataQuerySemanticAstSelectExpandClause.


        :return: The selected_items of this MicrosoftDataODataQuerySemanticAstSelectExpandClause.
        :rtype: list[MicrosoftDataODataQuerySemanticAstSelectItem]
        """
        return self._selected_items

    @selected_items.setter
    def selected_items(self, selected_items):
        """Sets the selected_items of this MicrosoftDataODataQuerySemanticAstSelectExpandClause.


        :param selected_items: The selected_items of this MicrosoftDataODataQuerySemanticAstSelectExpandClause.
        :type: list[MicrosoftDataODataQuerySemanticAstSelectItem]
        """

        self._selected_items = selected_items

    @property
    def all_selected(self):
        # type: () -> bool
        """Gets the all_selected of this MicrosoftDataODataQuerySemanticAstSelectExpandClause.


        :return: The all_selected of this MicrosoftDataODataQuerySemanticAstSelectExpandClause.
        :rtype: bool
        """
        return self._all_selected

    @all_selected.setter
    def all_selected(self, all_selected):
        """Sets the all_selected of this MicrosoftDataODataQuerySemanticAstSelectExpandClause.


        :param all_selected: The all_selected of this MicrosoftDataODataQuerySemanticAstSelectExpandClause.
        :type: bool
        """

        self._all_selected = all_selected

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(MicrosoftDataODataQuerySemanticAstSelectExpandClause, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MicrosoftDataODataQuerySemanticAstSelectExpandClause):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MicrosoftDataODataQuerySemanticAstSelectExpandClause):
            return True

        return self.to_dict() != other.to_dict()
