STANDARD_NUCLEOTIDES = ['A', 'C', 'G', 'T']
FROM_NUCLEOTIDE_ONE_LETTER_TOKEN = {
    'A': 'A',
    'C': 'C',
    'G': 'G',
    'T': 'T',
    'U': 'T',
    '-': 'Gap',
    '#': 'Mask',
    '@': 'Special',
    'R': 'R',
    'Y': 'Y',
    'S': 'S',
    'W': 'W',
    'K': 'K',
    'M': 'M',
    'B': 'B',
    'D': 'D',
    'H': 'H',
    'V': 'V',
    'N': 'N',
}
TO_NUCLEOTIDE_ONE_LETTER_TOKEN = {
    'A': 'A',
    'C': 'C',
    'G': 'G',
    'T': 'T',
    'U': 'U',
    'Gap': '-',
    'Mask': '#',
    'Special': '@',
    'R': 'R',
    'Y': 'Y',
    'S': 'S',
    'W': 'W',
    'K': 'K',
    'M': 'M',
    'B': 'B',
    'D': 'D',
    'H': 'H',
    'V': 'V',
    'N': 'N',
}
AMBIGUOUS_NUCLEOTIDES = ['R', 'Y', 'S', 'W', 'K', 'M', 'B', 'D', 'H', 'V', 'N']
COMPLEMENTARY_NUCLEOTIDES = {
    'A': 'T',
    'C': 'G',
    'G': 'C',
    'T': 'A',
    'U': 'A',
    'R': 'Y',
    'Y': 'R',
    'S': 'S',
    'W': 'W',
    'K': 'M',
    'M': 'K',
    'B': 'V',
    'D': 'H',
    'H': 'D',
    'V': 'B',
    'N': 'N',
    'Gap': 'Gap',
    'Other': 'Other',
    'Mask': 'Mask',
}