# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jijmodeling.protobuf.pb2.constraint_pb2 as constraint__pb2
import jijmodeling.protobuf.pb2.custom_penalty_term_pb2 as custom__penalty__term__pb2
import jijmodeling.protobuf.pb2.expression_pb2 as expression__pb2
import jijmodeling.protobuf.pb2.problem_pb2 as problem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x0cheader.proto\x12\x0bjijmodeling\x1a\x10\x63onstraint.proto\x1a\x19\x63ustom_penalty_term.proto\x1a\x10\x65xpression.proto\x1a\rproblem.proto\"\xed\x01\n\x06Header\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12'\n\x07problem\x18\x03 \x01(\x0b\x32\x14.jijmodeling.ProblemH\x00\x12-\n\nconstraint\x18\x04 \x01(\x0b\x32\x17.jijmodeling.ConstraintH\x00\x12=\n\x13\x63ustom_penalty_term\x18\x05 \x01(\x0b\x32\x1e.jijmodeling.CustomPenaltyTermH\x00\x12'\n\nexpression\x18\x06 \x01(\x0b\x32\x11.jijmodeling.ExprH\x00\x42\x06\n\x04\x62odyb\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "header_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _HEADER._serialized_start = 108
    _HEADER._serialized_end = 345
# @@protoc_insertion_point(module_scope)
