
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-30T19:32:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f67ff8bc22fcc72ead96eeeaef04173ed53650cb",
 "version": "5.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
