"""add stripe_customer

Revision ID: 3398d67a1567
Revises: f1ea99885270
Create Date: 2023-06-26 09:29:04.488273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3398d67a1567'
down_revision = 'f1ea99885270'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_customer')
    # ### end Alembic commands ###
