"""unify currency

Revision ID: 5252d44f6650
Revises: 277fecce5d8a
Create Date: 2023-05-09 15:13:31.782316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5252d44f6650'
down_revision = '277fecce5d8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill', 'currency')
    op.drop_column('client', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('bill', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
