"""add due_at

Revision ID: 750c2b11b496
Revises: 3398d67a1567
Create Date: 2023-06-27 09:08:28.500156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750c2b11b496'
down_revision = '3398d67a1567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('due_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'due_at')
    # ### end Alembic commands ###
