"""store payment payload required data

Revision ID: fda694e67f67
Revises: deffdb4ce76e
Create Date: 2023-07-04 21:17:13.544562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda694e67f67'
down_revision = 'deffdb4ce76e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('card_brand', sa.String(length=20), nullable=True))
    op.add_column('payment', sa.Column('card_last4', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'card_last4')
    op.drop_column('payment', 'card_brand')
    # ### end Alembic commands ###
