# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forall.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jijmodeling.protobuf.pb2.expression_pb2 as expression__pb2
import jijmodeling.protobuf.pb2.index_pb2 as index__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x66orall.proto\x12\x0bjijmodeling\x1a\x10\x65xpression.proto\x1a\x0bindex.proto"\\\n\nForallList\x12#\n\x07indices\x18\x01 \x03(\x0b\x32\x12.jijmodeling.Index\x12)\n\nexpr_nodes\x18\x02 \x03(\x0b\x32\x15.jijmodeling.ExprNodeb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "forall_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _FORALLLIST._serialized_start = 60
    _FORALLLIST._serialized_end = 152
# @@protoc_insertion_point(module_scope)
