# Generated by Django 4.1 on 2023-05-17 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreplus_notices", "0003_firebasedevice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firebasedevice",
            options={"verbose_name": "Firebase device"},
        ),
    ]
