
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-01T13:04:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ca6dae02c3d5ef81894d29bbb6f747c459bcfce",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
