
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-02T16:05:11+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "d14f83863b6faa3614212a48bc1cf91c25cdf685",
 "version": "0.4.8b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
