# HTTPS
EVENTS_API_ENDPOINT = "https://collector-api{}.zaikorea.org"
EVENTS_API_PATH = "/events"

ML_API_ENDPOINT = "https://ml-api{}.zaikorea.org"
ML_API_PATH_PREFIX = "/clients/{}/recommenders"
USER_RECOMMENDATION_PATH_PREFIX = "/user-recommendations"
RELATED_ITEMS_RECOMMENDATION_PATH_PREFIX = "/related-items"
RERANKING_RECOMMENDATION_PATH_PREFIX = "/reranking"


HMAC_ALGORITHM = "HmacSHA256"
HMAC_SCHEME = "ZAi"

# HTTP Custom Headers
ZAI_CLIENT_ID_HEADER = "X-ZAI-CLIENT-ID"
ZAI_UNIX_TIMESTAMP_HEADER = "X-ZAI-TIMESTAMP"
ZAI_AUTHORIZATION_HEADER = "X-ZAI-AUTHORIZATION"
ZAI_CALL_TYPE_HEADER = "X-ZAI-CALL-TYPE"
ZAI_CALL_TYPE = "sdk_call"

BATCH_REQUEST_CAP = 50
EPSILON = 1e-4
CONNECT_TIMEOUT_S = 10
READ_TIMEOUT_S = 30
