# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: array_length.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x61rray_length.proto\x12\x0bjijmodeling"\xe1\x01\n\x0b\x41rrayLength\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.jijmodeling.ArrayLength.Type\x12\x10\n\x08\x61rray_id\x18\x02 \x01(\x04\x12\x0c\n\x04\x61xis\x18\x03 \x01(\x04"\x84\x01\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10TYPE_PLACEHOLDER\x10\x01\x12\x10\n\x0cTYPE_ELEMENT\x10\x02\x12 \n\x1cTYPE_SUBSCRIPTED_PLACEHOLDER\x10\x03\x12\x1c\n\x18TYPE_SUBSCRIPTED_ELEMENT\x10\x04\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "array_length_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _ARRAYLENGTH._serialized_start = 36
    _ARRAYLENGTH._serialized_end = 261
    _ARRAYLENGTH_TYPE._serialized_start = 129
    _ARRAYLENGTH_TYPE._serialized_end = 261
# @@protoc_insertion_point(module_scope)
