# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: index.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bindex.proto\x12\x0bjijmodeling"G\n\x05Index\x12\x12\n\nelement_id\x18\x01 \x01(\x04\x12\x19\n\x0c\x63ondition_id\x18\x02 \x01(\x04H\x00\x88\x01\x01\x42\x0f\n\r_condition_idb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "index_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _INDEX._serialized_start = 28
    _INDEX._serialized_end = 99
# @@protoc_insertion_point(module_scope)
