# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: problem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jijmodeling.protobuf.pb2.constraint_pb2 as constraint__pb2
import jijmodeling.protobuf.pb2.custom_penalty_term_pb2 as custom__penalty__term__pb2
import jijmodeling.protobuf.pb2.expression_pb2 as expression__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rproblem.proto\x12\x0bjijmodeling\x1a\x10\x63onstraint.proto\x1a\x19\x63ustom_penalty_term.proto\x1a\x10\x65xpression.proto"\xf5\x03\n\x07Problem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12)\n\x05sense\x18\x03 \x01(\x0e\x32\x1a.jijmodeling.Problem.Sense\x12-\n\x12objective_function\x18\x04 \x01(\x0b\x32\x11.jijmodeling.Expr\x12:\n\x0b\x63onstraints\x18\x05 \x03(\x0b\x32%.jijmodeling.Problem.ConstraintsEntry\x12J\n\x14\x63ustom_penalty_terms\x18\x06 \x03(\x0b\x32,.jijmodeling.Problem.CustomPenaltyTermsEntry\x1aK\n\x10\x43onstraintsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.jijmodeling.Constraint:\x02\x38\x01\x1aY\n\x17\x43ustomPenaltyTermsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.jijmodeling.CustomPenaltyTerm:\x02\x38\x01"F\n\x05Sense\x12\x15\n\x11SENSE_UNSPECIFIED\x10\x00\x12\x12\n\x0eSENSE_MINIMIZE\x10\x01\x12\x12\n\x0eSENSE_MAXIMIZE\x10\x02\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "problem_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _PROBLEM_CONSTRAINTSENTRY._options = None
    _PROBLEM_CONSTRAINTSENTRY._serialized_options = b"8\001"
    _PROBLEM_CUSTOMPENALTYTERMSENTRY._options = None
    _PROBLEM_CUSTOMPENALTYTERMSENTRY._serialized_options = b"8\001"
    _PROBLEM._serialized_start = 94
    _PROBLEM._serialized_end = 595
    _PROBLEM_CONSTRAINTSENTRY._serialized_start = 357
    _PROBLEM_CONSTRAINTSENTRY._serialized_end = 432
    _PROBLEM_CUSTOMPENALTYTERMSENTRY._serialized_start = 434
    _PROBLEM_CUSTOMPENALTYTERMSENTRY._serialized_end = 523
    _PROBLEM_SENSE._serialized_start = 525
    _PROBLEM_SENSE._serialized_end = 595
# @@protoc_insertion_point(module_scope)
