# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthenticationService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SiLAFramework_pb2 as SiLAFramework__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x41uthenticationService.proto\x12\x34sila2.org.silastandard.core.authenticationservice.v1\x1a\x13SiLAFramework.proto\"\xf4\x01\n\x10Login_Parameters\x12:\n\x12UserIdentification\x18\x01 \x01(\x0b\x32\x1e.sila2.org.silastandard.String\x12\x30\n\x08Password\x18\x02 \x01(\x0b\x32\x1e.sila2.org.silastandard.String\x12\x37\n\x0fRequestedServer\x18\x03 \x01(\x0b\x32\x1e.sila2.org.silastandard.String\x12\x39\n\x11RequestedFeatures\x18\x04 \x03(\x0b\x32\x1e.sila2.org.silastandard.String\"~\n\x0fLogin_Responses\x12\x33\n\x0b\x41\x63\x63\x65ssToken\x18\x01 \x01(\x0b\x32\x1e.sila2.org.silastandard.String\x12\x36\n\rTokenLifetime\x18\x02 \x01(\x0b\x32\x1f.sila2.org.silastandard.Integer\"H\n\x11Logout_Parameters\x12\x33\n\x0b\x41\x63\x63\x65ssToken\x18\x01 \x01(\x0b\x32\x1e.sila2.org.silastandard.String\"\x12\n\x10Logout_Responses2\xd0\x02\n\x15\x41uthenticationService\x12\x98\x01\n\x05Login\x12\x46.sila2.org.silastandard.core.authenticationservice.v1.Login_Parameters\x1a\x45.sila2.org.silastandard.core.authenticationservice.v1.Login_Responses\"\x00\x12\x9b\x01\n\x06Logout\x12G.sila2.org.silastandard.core.authenticationservice.v1.Logout_Parameters\x1a\x46.sila2.org.silastandard.core.authenticationservice.v1.Logout_Responses\"\x00\x62\x06proto3')



_LOGIN_PARAMETERS = DESCRIPTOR.message_types_by_name['Login_Parameters']
_LOGIN_RESPONSES = DESCRIPTOR.message_types_by_name['Login_Responses']
_LOGOUT_PARAMETERS = DESCRIPTOR.message_types_by_name['Logout_Parameters']
_LOGOUT_RESPONSES = DESCRIPTOR.message_types_by_name['Logout_Responses']
Login_Parameters = _reflection.GeneratedProtocolMessageType('Login_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _LOGIN_PARAMETERS,
  '__module__' : 'AuthenticationService_pb2'
  # @@protoc_insertion_point(class_scope:sila2.org.silastandard.core.authenticationservice.v1.Login_Parameters)
  })
_sym_db.RegisterMessage(Login_Parameters)

Login_Responses = _reflection.GeneratedProtocolMessageType('Login_Responses', (_message.Message,), {
  'DESCRIPTOR' : _LOGIN_RESPONSES,
  '__module__' : 'AuthenticationService_pb2'
  # @@protoc_insertion_point(class_scope:sila2.org.silastandard.core.authenticationservice.v1.Login_Responses)
  })
_sym_db.RegisterMessage(Login_Responses)

Logout_Parameters = _reflection.GeneratedProtocolMessageType('Logout_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _LOGOUT_PARAMETERS,
  '__module__' : 'AuthenticationService_pb2'
  # @@protoc_insertion_point(class_scope:sila2.org.silastandard.core.authenticationservice.v1.Logout_Parameters)
  })
_sym_db.RegisterMessage(Logout_Parameters)

Logout_Responses = _reflection.GeneratedProtocolMessageType('Logout_Responses', (_message.Message,), {
  'DESCRIPTOR' : _LOGOUT_RESPONSES,
  '__module__' : 'AuthenticationService_pb2'
  # @@protoc_insertion_point(class_scope:sila2.org.silastandard.core.authenticationservice.v1.Logout_Responses)
  })
_sym_db.RegisterMessage(Logout_Responses)

_AUTHENTICATIONSERVICE = DESCRIPTOR.services_by_name['AuthenticationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGIN_PARAMETERS._serialized_start=107
  _LOGIN_PARAMETERS._serialized_end=351
  _LOGIN_RESPONSES._serialized_start=353
  _LOGIN_RESPONSES._serialized_end=479
  _LOGOUT_PARAMETERS._serialized_start=481
  _LOGOUT_PARAMETERS._serialized_end=553
  _LOGOUT_RESPONSES._serialized_start=555
  _LOGOUT_RESPONSES._serialized_end=573
  _AUTHENTICATIONSERVICE._serialized_start=576
  _AUTHENTICATIONSERVICE._serialized_end=912
# @@protoc_insertion_point(module_scope)
