# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscript.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fsubscript.proto\x12\x0bjijmodeling"\xcd\x01\n\tSubscript\x12\x0c\n\x04ndim\x18\x01 \x01(\x04\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.jijmodeling.Subscript.Type\x12\x13\n\x0bvariable_id\x18\x03 \x01(\x04\x12\x15\n\rsubscript_ids\x18\x04 \x03(\x04"[\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10TYPE_PLACEHOLDER\x10\x01\x12\x10\n\x0cTYPE_ELEMENT\x10\x02\x12\x15\n\x11TYPE_DECISION_VAR\x10\x03\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "subscript_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _SUBSCRIPT._serialized_start = 33
    _SUBSCRIPT._serialized_end = 238
    _SUBSCRIPT_TYPE._serialized_start = 147
    _SUBSCRIPT_TYPE._serialized_end = 238
# @@protoc_insertion_point(module_scope)
