
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-02T11:25:29+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9021f624b28564ce2aad1b12d59bf68a6a636bd",
 "version": "0.4.8b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
